name: artifact

on: push

env:
  ARTIFACT_NAME: artifact_Learning
  
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: check out the code
        uses: actions/checkout@v3
      - name: upload the artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .
