name: first

on: [push, pull_request]

jobs:
  job1:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: step one
        uses: actions/checkout@v3
      - name: step two
        run: env | sort

  job2:
    name: second job
    runs-on: windows-latest
    steps:
      - name: step one
        uses: actions/checkout@v3
      - name: step two
        run: "Get-ChildItem Env: | Sort-Object Name"

  job3:
    name: third job
    runs-on: ubuntu-latest
    steps:
      # needs: [job1, job2]
      - name: step one
        uses: actions/checkout@v3
      - name: step two
        run: echo "Babak this is the third job"
